import type { Metadata } from "next";
import { DM_Sans, Inter, Montserrat, Playfair_Display } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  display: "swap",
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair-display",
  display: "swap",
});

const  dm_sans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-dm-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Transparent Governance Foundation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-white">
      <link
        rel="icon"
        href="./logo.svg"
        type="image/svg"
    sizes="any"
      />
      <body
        className={`${playfair.variable} ${montserrat.variable} ${dm_sans.variable} font-montserrat`}
      >
        <NavBar />
        <div className="min-h-screen mt-[5rem]">
        {children}
        </div>
        <Footer />
        
      </body>
    </html>
  );
}
